-- ============================================================================
-- LearnAI — Seed Esteso per Catalogo Corsi di Laurea (area Onboarding Ospiti)
-- Questo file crea (se non esiste) e popola la tabella corsi_di_laurea_onboarding.
-- Idempotente: può essere eseguito più volte senza duplicati.
-- ============================================================================

PRAGMA foreign_keys = OFF;

-- Crea la tabella se non esiste
CREATE TABLE IF NOT EXISTS corsi_di_laurea_onboarding (
    id                 INTEGER PRIMARY KEY AUTOINCREMENT,
    nome               TEXT    NOT NULL,
    facolta            TEXT    NOT NULL,
    descrizione        TEXT,
    durata             TEXT,
    tipo_accesso       TEXT,
    sbocchi_lavorativi TEXT,
    created_at         DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Elimina i record esistenti e reinserisce tutto in modo idempotente
DELETE FROM corsi_di_laurea_onboarding;

INSERT INTO corsi_di_laurea_onboarding (id, nome, facolta, descrizione, durata, tipo_accesso, sbocchi_lavorativi) VALUES
-- INGEGNERIA
(1,  'Ingegneria Informatica',          'Ingegneria',
     'Progettazione di sistemi hardware e software, reti, sistemi operativi e architetture degli elaboratori. Forma figure tecniche capaci di sviluppare applicazioni complesse, gestire infrastrutture IT e lavorare nell''intelligenza artificiale.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Software engineer, system architect, AI engineer, DevOps engineer, CTO, consulente IT'),
(2,  'Informatica',                     'Scienze MM.FF.NN.',
     'Fondamenti teorici e applicativi dell''informatica: algoritmi, intelligenza artificiale, crittografia e sicurezza informatica. Ideale per chi vuole lavorare come data scientist, software engineer o ricercatore IT.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Data scientist, software engineer, ricercatore IT, esperto cybersecurity, analista dati'),
(3,  'Ingegneria Elettronica',          'Ingegneria',
     'Progettazione di componenti e sistemi elettronici, microelettronica, sensori e sistemi embedded. Apre le porte all''industria automotive, ai dispositivi medici e all''elettronica di consumo.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Progettista elettronico, ingegnere embedded, R&D automotive, progettista dispositivi medici'),
(4,  'Ingegneria Meccanica',            'Ingegneria',
     'Progettazione e realizzazione di macchine, sistemi meccanici, impianti industriali e produzione manifatturiera. Cruciale per l''industria 4.0, l''automotive e l''aerospazio.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Progettista meccanico, responsabile produzione, ingegnere automotive, ingegnere aerospaziale'),
(5,  'Ingegneria Civile',               'Ingegneria',
     'Progettazione e costruzione di infrastrutture civili: strade, ponti, edifici e opere idrauliche. Forma professionisti per enti pubblici, imprese edili e libera professione.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Ingegnere strutturista, direttore lavori, progettista infrastrutture, libero professionista'),
(6,  'Ingegneria Aerospaziale',         'Ingegneria',
     'Progettazione e gestione di velivoli, veicoli spaziali e sistemi aeronautici. Forma ingegneri per l''industria aeronautica, enti spaziali (ASI/ESA) e la Difesa.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Ingegnere aeronautico, progettista spaziale, ricercatore ASI/ESA, ingegnere della Difesa'),
(7,  'Ingegneria Biomedica',            'Ingegneria',
     'Applicazione dell''ingegneria alla medicina: dispositivi medici, diagnostica per immagini e biomateriali. Ideale per chi vuole unire tecnologia e salute.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Ingegnere clinico, progettista dispositivi medici, ricercatore biomedicale, R&D farmaceutico'),
(8,  'Ingegneria Gestionale',           'Ingegneria',
     'Unisce competenze ingegneristiche con management aziendale, logistica, supply chain e analisi dei dati. Forma operations manager, consulenti e project manager.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Operations manager, consulente strategico, project manager, supply chain manager, business analyst'),
(9,  'Ingegneria delle Telecomunicazioni', 'Ingegneria',
     'Reti di comunicazione, trasmissione dati, media digitali e tecnologie 5G/6G. Forma ingegneri per telco, broadcasting digitale e ricerca sulla rete.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Network engineer, ingegnere telco, esperto 5G/6G, progettista reti, ricercatore TLC'),
(10, 'Architettura (Ciclo Unico)',      'Architettura',
     'Percorso abilitante alla professione di architetto: progettazione architettonica, urbanistica, restauro e costruzione sostenibile.',
     '5 anni (ciclo unico)',
     'Programmato locale',
     'Architetto libero professionista, urbanista, restauratore, progettista edilizia sostenibile'),
-- ECONOMIA
(11, 'Economia Aziendale',              'Economia',
     'Fondamenti di gestione aziendale, contabilita, finanza d''impresa e strategia organizzativa. Forma manager, commercialisti, controller e analisti finanziari.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Commercialista, controller, analista finanziario, manager aziendale, revisore contabile'),
(12, 'Economia e Commercio',            'Economia',
     'Formazione in micro e macroeconomia, econometria, economia internazionale e politiche pubbliche. Ideale per chi vuole lavorare in enti internazionali, banche o pubblica amministrazione.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Economista, funzionario enti internazionali, analista bancario, esperto politiche pubbliche'),
(13, 'Finanza',                         'Economia',
     'Formazione specialistica in finanza quantitativa, mercati dei capitali, derivati e risk management. Apre le porte all''investment banking, gestione portafogli e consulenza finanziaria.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Investment banker, portfolio manager, risk manager, analista quantitativo, consulente finanziario'),
-- GIURISPRUDENZA
(14, 'Giurisprudenza',                  'Giurisprudenza',
     'Formazione giuridica completa in diritto civile, penale, costituzionale, amministrativo, commerciale e internazionale. Forma avvocati, magistrati, notai e funzionari pubblici.',
     '5 anni (ciclo unico)',
     'Libero',
     'Avvocato, magistrato, notaio, funzionario pubblico, giurista d''impresa, diplomatico'),
-- MEDICINA
(15, 'Medicina e Chirurgia',            'Medicina e Chirurgia',
     'Formazione medica completa per il conseguimento dell''abilitazione alla professione di medico chirurgo. Include tirocinio pratico e preparazione all''esame di Stato.',
     '6 anni (ciclo unico)',
     'Programmato nazionale (test TOLC-MED)',
     'Medico chirurgo, medico specialista, medico di base, ricercatore clinico, dirigente sanitario'),
(16, 'Infermieristica',                 'Medicina e Chirurgia',
     'Formazione dell''infermiere professionale per la cura e l''assistenza del paziente in ambito ospedaliero e territoriale. Triennale abilitante.',
     '3 anni (triennale abilitante)',
     'Programmato locale',
     'Infermiere ospedaliero, infermiere territoriale, coordinatore infermieristico, infermiere libero professionista'),
(17, 'Fisioterapia',                    'Medicina e Chirurgia',
     'Riabilitazione funzionale di pazienti con patologie ortopediche, neurologiche e cardiorespiratorie. Percorso pratico con tirocini fin dal primo anno.',
     '3 anni (triennale abilitante)',
     'Programmato locale',
     'Fisioterapista SSN, fisioterapista sportivo, libero professionista, ricercatore riabilitativo'),
(18, 'Farmacia',                        'Farmacia',
     'Formazione completa per la professione di farmacista: sintesi, analisi, distribuzione e counselling del farmaco. Percorso abilitante.',
     '5 anni (ciclo unico)',
     'Programmato locale',
     'Farmacista, ricercatore farmaceutico, informatore scientifico, responsabile qualita farmaceutica'),
-- SCIENZE MM.FF.NN.
(19, 'Matematica',                      'Scienze MM.FF.NN.',
     'Fondamenti e applicazioni della matematica pura e applicata: analisi, algebra, geometria, probabilita e statistica. Percorso altamente formativo per menti analitiche.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Ricercatore matematico, analista quantitativo, attuario, data scientist, docente'),
(20, 'Fisica',                          'Scienze MM.FF.NN.',
     'Principi fondamentali della fisica: meccanica, elettromagnetismo, fisica moderna e quantum computing. Forma ricercatori, fisici industriali e data scientist di alto profilo.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Ricercatore fisico, fisico industriale, data scientist, esperto quantum computing, docente'),
(21, 'Chimica',                         'Scienze MM.FF.NN.',
     'Studio delle proprieta e delle trasformazioni della materia. Apre le porte all''industria farmaceutica, chimica, alimentare e alla ricerca scientifica.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Chimico industriale, ricercatore R&D, analista di laboratorio, responsabile qualita'),
(22, 'Biologia',                        'Scienze MM.FF.NN.',
     'Studio degli esseri viventi, dalla cellula all''ecosistema. Approccio sperimentale con laboratori e tirocini sul campo.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Biologo ricercatore, biologo nutrizionista, biologo ambientale, informatore scientifico, docente'),
-- LETTERE & SCIENZE UMANE
(23, 'Lettere e Filosofia',             'Lettere',
     'Studio approfondito di letteratura, storia, filosofia e lingue classiche. Forma insegnanti, ricercatori, giornalisti e professionisti della comunicazione culturale.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Docente, giornalista, ricercatore umanistico, curatore culturale, redattore editoriale'),
(24, 'Psicologia',                      'Scienze Politiche e Sociali',
     'Studio del comportamento umano, processi cognitivi e relazioni sociali. Per l''abilitazione alla professione di psicologo e necessaria la magistrale e il tirocinio.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Psicologo clinico, psicologo del lavoro (HR), psicoterapeuta, neuropsicologo, ricercatore'),
(25, 'Scienze della Comunicazione',     'Scienze Politiche e Sociali',
     'Media, giornalismo, marketing digitale, comunicazione pubblica e corporate. Forma professionisti della comunicazione per agenzie, aziende e media company.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Social media manager, giornalista, PR specialist, copywriter, digital marketing manager'),
(26, 'Scienze dell''Educazione',        'Scienze Politiche e Sociali',
     'Pedagogia e scienze dell''educazione per la formazione di educatori, pedagogisti e professionisti del mondo scolastico ed extrascolastico.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Educatore professionale, pedagogista, coordinatore servizi educativi, formatore aziendale'),
-- AGRARIA
(27, 'Scienze Agrarie',                 'Agraria',
     'Formazione sulle tecniche agronomiche, zootecniche e di gestione forestale e ambientale in ottica di sostenibilita. Include attivita di campo e laboratorio.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Agronomo, consulente agricolo, tecnico ambientale, responsabile sostenibilita, perito agrario'),
(28, 'Scienze e Tecnologie Alimentari', 'Agraria',
     'Formazione sulle tecniche di produzione, trasformazione e controllo qualita nell''industria agroalimentare. Forte componente di laboratorio e tirocini in azienda.',
     '3 anni (triennale) + 2 anni (magistrale)',
     'Libero',
     'Tecnologo alimentare, responsabile produzione, quality manager, ricercatore R&D agroalimentare');

PRAGMA foreign_keys = ON;

-- ============================================================================
-- RIEPILOGO: 28 corsi di laurea con nome, facolta, descrizione, durata,
--            tipo di accesso e sbocchi lavorativi per l'onboarding ospiti
-- ============================================================================
